[buildPlans.MarcoCustom]
family = "marco-custom"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.MarcoCustom.variants.design]
capital-a = "curly-serifless"
capital-j = "serifed-both-sides"
capital-l = "serifless"
capital-p = "closed-motion-serifed"
capital-q = "crossing"
capital-z = "curly-serifless-with-crossbar"
f = "flat-hook-tailed"
g = "double-storey-open"
i = "zshaped"
k = "curly-serifless"
l = "tailed-serifed"
m = "top-left-serifed"
n = "straight-top-left-serifed"
q = "straight-motion-serifed"
r = "top-serifed"
x = "semi-chancery-straight"
y = "straight-turn-motion-serifed"
z = "curly-serifless-with-crossbar"
lower-delta = "flat-top"
lower-lambda = "tailed-turn"
one = "no-base-flat-top-serif"
three = "two-arcs"
four = "closed-serifed"
six = "straight-bar"
seven = "bend-serifless-crossbar"
eight = "two-circles"
nine = "straight-bar"
punctuation-dot = "round"
asterisk = "hex-mid"
underscore = "high"
paren = "normal"
brace = "curly-flat-boundary"
guillemet = "straight"
at = "fourfold-tall"
dollar = "interrupted"
question = "smooth"
micro-sign = "tailed-motion-serifed"
lig-ltgteq = "slanted"

  [buildPlans.MarcoCustom.ligations]
  inherits = "dlig"
